window.WARNERS_PRODUCTS = [
  {
    id: "ultrabook-pro-14",
    name: "UltraBook Pro 14",
    category: "Laptops",
    brand: "WarnerTech",
    price: 1299,
    stock: 42,
    weight: 0.92,
    subtitle: "Laptop • Intel i7",
    description: "Powerful 14-inch laptop for students and professionals",
    tags: ["Intel i7", "16GB RAM", "512GB SSD"],
    specs: [
      "14-inch display with lightweight design",
      "Long battery life suitable for study and work",
      "Compatible with USB-C accessories and laptop bag",
    ],
    tone: "lavender",
    emoji: "💻",
  },
  {
    id: "smartphone-x2",
    name: "SmartPhone X2",
    category: "Smartphones",
    brand: "SmartCore",
    price: 899,
    stock: 65,
    weight: 0.88,
    subtitle: "Phone • 128GB",
    description: "Fast dual-camera smartphone with all-day battery.",
    tags: ["5G", "128GB", "OLED"],
    specs: ["6.5-inch OLED display", "5G connectivity", "Fast charging"],
    tone: "blue",
    emoji: "📱",
  },
  {
    id: "noise-free-headset",
    name: "Noise-Free Headset",
    category: "Audio",
    brand: "LogiSound",
    price: 179,
    stock: 57,
    weight: 0.79,
    subtitle: "Audio • Bluetooth",
    description: "Comfortable over-ear headset with noise reduction.",
    tags: ["ANC", "Bluetooth", "USB"],
    specs: ["Active noise reduction", "Soft ear cushions", "USB / Bluetooth"],
    tone: "mint",
    emoji: "🎧",
  },
  {
    id: "smart-home-hub",
    name: "Smart Home Hub",
    category: "Smart Home",
    brand: "WarnerTech",
    price: 249,
    stock: 38,
    weight: 0.7,
    subtitle: "Home automation",
    description: "Control lights, plugs and sensors from one hub.",
    tags: ["App control", "Wi-Fi"],
    specs: ["App control", "Works with major brands", "Easy setup"],
    tone: "slate",
    emoji: "🏠",
  },
  {
    id: "wireless-mouse",
    name: "Wireless Mouse",
    category: "Accessories",
    brand: "LogiSound",
    price: 39,
    stock: 150,
    weight: 0.76,
    subtitle: "Accessory • Popular",
    description: "Ergonomic wireless mouse for everyday use.",
    tags: ["2.4GHz", "Silent"],
    specs: ["Silent clicks", "Long battery life", "USB receiver"],
    tone: "mint",
    emoji: "🖱️",
  },
  {
    id: "laptop-sleeve",
    name: "Laptop Sleeve",
    category: "Accessories",
    brand: "WarnerTech",
    price: 49,
    stock: 94,
    weight: 0.81,
    subtitle: "Accessory • 14 inch",
    description: "Padded sleeve for 14-inch laptops.",
    tags: ["14 inch", "Padded"],
    specs: ["Soft lining", "Slim profile", "Fits UltraBook Pro 14"],
    tone: "lavender",
    emoji: "💼",
  },
  {
    id: "usb-c-hub",
    name: "USB-C Hub",
    category: "Accessories",
    brand: "SmartCore",
    price: 69,
    stock: 80,
    weight: 0.74,
    subtitle: "Accessory • Recommended",
    description: "Expand ports on modern laptops.",
    tags: ["USB-C", "HDMI"],
    specs: ["HDMI out", "USB-A ports", "SD card reader"],
    tone: "mint",
    emoji: "🔌",
  },
  {
    id: "portable-ssd",
    name: "Portable SSD",
    category: "Accessories",
    brand: "SmartCore",
    price: 129,
    stock: 61,
    weight: 0.77,
    subtitle: "Storage • Fast",
    description: "Fast portable storage for files and media.",
    tags: ["1TB", "USB-C"],
    specs: ["High transfer speed", "Compact", "Shock resistant"],
    tone: "blue",
    emoji: "💾",
  },
  {
    id: "laptop-stand",
    name: "Laptop Stand",
    category: "Accessories",
    brand: "WarnerTech",
    price: 59,
    stock: 70,
    weight: 0.72,
    subtitle: "Desk setup",
    description: "Aluminum stand for better desk posture.",
    tags: ["Aluminum", "Adjustable"],
    specs: ["Ergonomic height", "Stable base", "Cable friendly"],
    tone: "slate",
    emoji: "🖥️",
  },
  {
    id: "bluetooth-keyboard",
    name: "Bluetooth Keyboard",
    category: "Accessories",
    brand: "LogiSound",
    price: 79,
    stock: 88,
    weight: 0.73,
    subtitle: "Accessory",
    description: "Compact wireless keyboard for work and study.",
    tags: ["Bluetooth", "Quiet"],
    specs: ["Multi-device pair", "Rechargeable", "Quiet keys"],
    tone: "lavender",
    emoji: "⌨️",
  },
  {
    id: "tablet-air-11",
    name: "Tablet Air 11",
    category: "Tablets",
    brand: "WarnerTech",
    price: 599,
    stock: 28,
    weight: 0.84,
    subtitle: "Tablet • 128GB",
    description: "Lightweight tablet for reading, notes and streaming.",
    tags: ["11-inch", "Stylus"],
    specs: ["11-inch display", "Stylus support", "All-day battery"],
    tone: "blue",
    emoji: "📲",
  },
];

window.WARNERS_CATEGORIES = [
  "Laptops",
  "Smartphones",
  "Audio",
  "Accessories",
  "Smart Home",
  "Tablets",
];

window.WARNERS_USERS = {
  admin: { password: "admin", role: "admin", label: "Admin", initial: "A" },
  owner: { password: "owner", role: "owner", label: "Owner", initial: "O" },
};
