window.WARNERS_PRODUCTS = [
  {
    id: "ultrabook-pro-14",
    name: "UltraBook Pro 14",
    category: "Laptops",
    price: 1299,
    stock: 42,
    subtitle: "Laptop • Intel i7",
    description: "Powerful 14-inch laptop for students and professionals.",
    specs: [
      "14-inch display with lightweight design",
      "Long battery life for study and work",
      "USB-C accessories compatible",
    ],
    tone: "lavender",
    emoji: "💻",
  },
  {
    id: "smartphone-x2",
    name: "SmartPhone X2",
    category: "Smartphones",
    price: 899,
    stock: 65,
    subtitle: "Phone • 128GB",
    description: "Fast dual-camera smartphone with all-day battery.",
    specs: ["6.5-inch OLED display", "5G connectivity", "Fast charging"],
    tone: "sky",
    emoji: "📱",
  },
  {
    id: "noise-free-headset",
    name: "Noise-Free Headset",
    category: "Audio",
    price: 179,
    stock: 57,
    subtitle: "Audio • Work setup",
    description: "Comfortable over-ear headset with noise reduction.",
    specs: ["Active noise reduction", "Soft ear cushions", "USB / Bluetooth"],
    tone: "mint",
    emoji: "🎧",
  },
  {
    id: "wireless-mouse-pro",
    name: "Wireless Mouse Pro",
    category: "Accessories",
    price: 49,
    stock: 120,
    subtitle: "Accessory • Office",
    description: "Ergonomic wireless mouse for everyday use.",
    specs: ["Silent clicks", "Long battery life", "2.4GHz receiver"],
    tone: "slate",
    emoji: "🖱️",
  },
  {
    id: "smart-hub-mini",
    name: "Smart Hub Mini",
    category: "Smart Home",
    price: 129,
    stock: 38,
    subtitle: "Smart Home • Hub",
    description: "Compact hub to connect lights, plugs and sensors.",
    specs: ["App control", "Works with major brands", "Easy setup"],
    tone: "sand",
    emoji: "🏠",
  },
  {
    id: "tablet-air-11",
    name: "Tablet Air 11",
    category: "Tablets",
    price: 599,
    stock: 28,
    subtitle: "Tablet • 128GB",
    description: "Lightweight tablet for reading, notes and streaming.",
    specs: ["11-inch display", "Stylus support", "All-day battery"],
    tone: "lavender",
    emoji: "📲",
  },
];

window.WARNERS_CATEGORIES = [
  "Laptops",
  "Smartphones",
  "Audio",
  "Accessories",
  "Smart Home",
  "Tablets",
];

window.WARNERS_RULES = [
  {
    name: "Laptop bag with UltraBook",
    when: "View UltraBook Pro 14",
    then: "Recommend laptop bag",
  },
  {
    name: "Earbuds with SmartPhone",
    when: "Add SmartPhone X2 to cart",
    then: "Recommend wireless earbuds",
  },
  {
    name: "Mouse with headset",
    when: "Buy Noise-Free Headset",
    then: "Suggest Wireless Mouse Pro",
  },
];
